Repository josoavj/Prospectius, pull requests merged in 2024-10, with the labels that each got.

#6 Suppression
  .idea/.gitignore
  .idea/Prospectius.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Assets/CL.JPG
  Assets/CLM.JPG
  Assets/IMG_7268.PNG
  Assets/Ispm.png
  Assets/calendar.png
  Assets/eye.png
  Assets/logout.PNG
  Assets/user.jpg
  Poppins/OFL.txt
  Poppins/Poppins-Black.ttf
  Poppins/Poppins-BlackItalic.ttf
  Poppins/Poppins-Bold.ttf
  Poppins/Poppins-BoldItalic.ttf
  Poppins/Poppins-ExtraBold.ttf
  Poppins/Poppins-ExtraBoldItalic.ttf
  Poppins/Poppins-ExtraLight.ttf
  Poppins/Poppins-ExtraLightItalic.ttf
  Poppins/Poppins-Italic.ttf
  Poppins/Poppins-Light.ttf
  Poppins/Poppins-LightItalic.ttf
  Poppins/Poppins-Medium.ttf
  Poppins/Poppins-MediumItalic.ttf
  Poppins/Poppins-Regular.ttf
  Poppins/Poppins-SemiBold.ttf
  Poppins/Poppins-SemiBoldItalic.ttf
  Poppins/Poppins-Thin.ttf
  Poppins/Poppins-ThinItalic.ttf
  README.md
  Screen/Blogin.kv
  Screen/Create.kv
  Screen/Dialog.kv
  Screen/Home.kv
  Screen/Login.kv
  Screen/New.kv
  Screen/Suivi.kv
  Test.py
  main.py
Labels: good first issue

#7 Nouveau élément
  .idea/.gitignore
  .idea/Suivie_de_prospection.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  Assets/CL.JPG
  Assets/CLM.JPG
  Assets/calendar.png
  Assets/eye.png
  Assets/logout.PNG
  Assets/user.jpg
  Final.sql
  Poppins/OFL.txt
  Poppins/Poppins-Black.ttf
  Poppins/Poppins-BlackItalic.ttf
  Poppins/Poppins-Bold.ttf
  Poppins/Poppins-BoldItalic.ttf
  Poppins/Poppins-ExtraBold.ttf
  Poppins/Poppins-ExtraBoldItalic.ttf
  Poppins/Poppins-ExtraLight.ttf
  Poppins/Poppins-ExtraLightItalic.ttf
  Poppins/Poppins-Italic.ttf
  Poppins/Poppins-Light.ttf
  Poppins/Poppins-LightItalic.ttf
  Poppins/Poppins-Medium.ttf
  Poppins/Poppins-MediumItalic.ttf
  Poppins/Poppins-Regular.ttf
  Poppins/Poppins-SemiBold.ttf
  Poppins/Poppins-SemiBoldItalic.ttf
  Poppins/Poppins-Thin.ttf
  Poppins/Poppins-ThinItalic.ttf
  Screen/Blogin.kv
  Screen/Create.kv
  Screen/Home.kv
  Screen/Login.kv
  Screen/New.kv
  Screen/Suivi.kv
  main.py
Labels: enhancement

#8 Create README.md
  README.md
Labels: documentation
